import type { Metadata } from "next";
import { Geist, Geist_Mono, Arvo, Open_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const arvoFont = Arvo({
  variable: "--font-arvo",
  subsets: ["latin"],
  weight: "700"
})

const openSans = Open_Sans({
  variable: "--font-opensans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "just do it.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${arvoFont.variable} ${openSans.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
